---
title: "Core_Isotopes"
author: "Balint"
date: "10/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

Import Data:

```{r}
#load libraries
library(readxl)
library(tidyverse)

#import data
isotopes_2 <- read_excel("data/isotopes_2.xlsx") %>%
  group_by(Location,`Depth`) %>%
  summarize(`%N`=mean(`%N`),
            d15N=mean(d15N),
            `%C.total`=mean(`%C.total`),
            d13C.total=mean(d13C.total))

all_isotopes <- read_excel("data/isotopes_tidy.xlsx")

colnames(all_isotopes) <- c("Core","Location","Depth","Water","Bulk","Grainsize","d15N","%N","d13C.total","d13C.inorg","%C.total","%C.organic","%C.inorg","% inorg","C:N", '%P.total','N:P')

all_isotopes <- all_isotopes %>%
  drop_na("d15N")

all_isotopes <- full_join(all_isotopes,isotopes_2)

```

Plot isotope data:

```{r}
theme_set(theme_bw())

subset <- all_isotopes[c("Location","Depth","d15N", "d13C.total")]

#subset <- subset(subset,subset$`%C.organic`<10)

subset <- pivot_longer(subset,cols=3:ncol(subset))

subset$name <- factor(
  subset$name,
  labels=c(
    bquote(delta^13*C~'(‰)'),
    bquote(delta^15*N~'(‰)')
    )
  )

subset$Location <- factor(
  subset$Location,
  levels=c('North','Middle','South')
  )

ggplot(subset, aes(x=Depth, y=value, group=Location))+
  geom_smooth(aes(color=Location), alpha=0.5, se=FALSE)+
  geom_point(shape=21, size=2.5, aes(fill=Location))+
  coord_flip()+
  #scale_x_reverse(labels=function(x)2020-(x*3))+
  scale_x_reverse()+
  facet_wrap(~name,
             nrow=1,
             scales="free_x",
             strip.position = "bottom",
             labeller = label_parsed
             )+
  ylab(NULL) +
  theme(
    strip.background = element_blank(),
    strip.placement = "outside",
    )+
  xlab("Depth (cm)")+
  scale_color_manual(
    values=c(
      "#E69F00", "#999999", "#56B4E9"
      )
  )+
  scale_fill_manual(
    values=c(
      "#E69F00", "#999999", "#56B4E9"
      )
  )

ggsave("figures/isotopes.png",width=8, height=4.5)

```

```{r}

subset <- all_isotopes[c("Location","Depth",'C:N',"N:P", "d15N")]

#subset <- subset(subset,subset$`%C.organic`<10)

subset <- pivot_longer(subset,cols=3:ncol(subset))

subset$name <- factor(
  subset$name,
  levels=c("C:N","N:P","d15N"),
  labels=c(
    bquote('C:N'~'Ratio'),
    bquote('N:P'~'Ratio'),
    bquote(delta^15*N~'(‰)')
    )
  )

subset$Location <- factor(
  subset$Location,
  levels=c('North','Middle','South')
  )

ggplot(subset, aes(x=Depth, y=value, group=Location))+
  geom_smooth(aes(color=Location), alpha=0.5, se=FALSE)+
  geom_point(shape=21, size=2.5, aes(fill=Location))+
  coord_flip()+
  #scale_x_reverse(labels=function(x)2020-(x*3))+
  scale_x_reverse()+
  facet_wrap(~name,
             nrow=1,
             scales="free_x",
             strip.position = "bottom",
             labeller = label_parsed
             )+
  ylab(NULL) +
  theme(
    strip.background = element_blank(),
    strip.placement = "outside",
    legend.position = c(0.74, 0.838),
    legend.background = element_rect(fill="white",
                                  linetype="solid", 
                                  colour ="black")
    )+
  xlab("Depth (cm)")+
  scale_color_manual(
    values=c(
      "#E69F00", "#999999", "#56B4E9"
      )
  )+
  scale_fill_manual(
    values=c(
      "#E69F00", "#999999", "#56B4E9"
      )
  )

ggsave("figures/elemental_ratios.png",width=8, height=4.5)

```


```{r}

subset <- all_isotopes[c("Location","Depth",'%N', "%C.organic",'%P.total')]

subset <- subset(subset,subset$`%C.organic`<10)

subset <- pivot_longer(subset,cols=3:ncol(subset))

subset$name <- factor(
  subset$name,
  labels=c(
    bquote(C[Organic]~'(%)'),
    bquote(N~'(%)'),
    bquote(P[Total]~x~10^-2~'(%)')
    )
  )

subset$Location <- factor(
  subset$Location,
  levels=c('North','Middle','South')
  )

ggplot(subset, aes(x=Depth, y=value, group=Location))+
  geom_smooth(aes(color=Location), alpha=0.5, se=FALSE)+
  geom_point(shape=21, size=2.5, aes(fill=Location))+
  coord_flip()+
  scale_x_reverse()+
  facet_wrap(~name,
             nrow=1,
             scales="free_x",
             strip.position = "bottom",
             labeller = label_parsed
             )+
  ylab(NULL) +
  theme(
    strip.background = element_blank(),
    strip.placement = "outside",
    legend.position = c(0.74, 0.838),
    legend.background = element_rect(fill="white",
                                  linetype="solid", 
                                  colour ="black"))+
  xlab("Depth (cm)")+
  scale_color_manual(
    values=c(
      "#E69F00", "#999999", "#56B4E9"
      )
  )+
  scale_fill_manual(
    values=c(
      "#E69F00", "#999999", "#56B4E9"
      )
  )

ggsave("figures/elemental_composition_3.png",width=8, height=4.5)

```


```{R}

subset <- all_isotopes[c("Location","Depth",'N:P')]

subset$Location <- factor(
  subset$Location,
  levels=c('North','Middle','South')
  )

ggplot(subset, aes(x=Depth, y=`N:P`, group=Location))+
  geom_smooth(aes(color=Location), alpha=0.5, se=FALSE)+
  geom_point(shape=21, size=2.5, aes(fill=Location))+
  coord_flip()+
  scale_x_reverse()+
  ylab(NULL) +
  theme(
    strip.background = element_blank(),
    strip.placement = "outside")+
  labs(x="Depth (cm)",
       y="N:P Ratio")+
  scale_color_manual(
    values=c(
      "#E69F00", "#999999", "#56B4E9"
      )
  )+
  scale_fill_manual(
    values=c(
      "#E69F00", "#999999", "#56B4E9"
      )
  )+
  geom_hline(yintercept=16,linetype="dashed")

ggsave("figures/NP_Ratio_2.png",width=6, height=6)


```