---
title: "data_processing"
author: "Balint"
date: "3/1/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

Import grainsize

```{r grainsize}
library(readxl)
library(tidyverse)

#import data
grain <- read_excel("data/grainsize_tidy.xlsx")

#remove replicate information
grain[c(2,4:5)] <- NULL

#create a list of cores
size_classes <- c("Clay","V.F. Silt","F. Silt","M. Silt","C. Silt","V.C. Silt","V.F. Sand","F. Sand","Sand","C. Sand","V.C. Sand","V.F. Gravel")

grainsizes <- data.frame(size_classes,c(2,4,8,16,31,62,125,250,500,1000,2000,4000))

colnames(grainsizes) <- c("Classification","Micrometers")

core_list <- c("North", "Middle", "South")

grain_class <- data.frame(matrix(nrow=0,ncol=6))

#iterate over list
for (i in core_list){
  temp_df <- subset(grain,Location==i)
  temp_df[1] <- NULL  
  temp_df <- aggregate(temp_df,list(temp_df$Depth),mean)
  temp_df[1] <- NULL
  temp_df <- pivot_longer(temp_df,!Depth,names_to="Grainsize",values_to="Percentage")
  temp_df$Grainsize <- as.numeric(as.character(temp_df$Grainsize))
  temp_df$Class <- NA
  for (x in 1:nrow(temp_df)){
    for (y in 1:nrow(grainsizes)){
      if (temp_df$Grainsize[x]<grainsizes[y,2]){
        temp_df$Class[x] <- grainsizes[y,1]
        break
      }
    }
  }
  temp_df$Location <- i
  if (i == "North"){
    temp_df$Core <- "AC2"
  }
  if (i == "Middle"){
    temp_df$Core <- "M6"
  }
  if (i == "South"){
    temp_df$Core <- "S3"
  }
  grain_class <- rbind(grain_class,temp_df)
  grain_class$Class <- factor(grain_class$Class,
                                  levels=size_classes)
  grain_class$Location <- factor(grain_class$Location,
                                  levels=c("North","Middle","South"))
}

write.csv(grain_class, "data/export/grainsize.csv")

```

```{r isotopes}
iso <- read_excel("data/irms_pelletier.xlsx")

iso <- iso[,c(4:6,10:13)]

colnames(iso) <- c("Location","Depth","Type","%N","d15N","%C","d13C")

iso_mean <- iso %>%
  group_by(Location,Depth,Type) %>%
  summarize(`%N`=mean(`%N`),
            d15N=mean(d15N),
            `%C`=mean(`%C`),
            d13C=mean(d13C))

iso_acid <- subset(iso_mean,Type=="Acidified")
iso_acid <- iso_acid[,c(1:2,6:7)] %>%
  rename("%C.org"="%C",
         "d13C.org"="d13C")

iso_unac <- subset(iso_mean,Type=="Unacidified")
iso_unac <- iso_unac[,c(1:2,4:7)] %>%
  rename("%C.total"="%C",
         "d13C.total"="d13C")

iso <- full_join(iso_acid,iso_unac)
iso$`%C.inorg` <- iso$`%C.total`-iso$`%C.org`

write.csv(iso, "data/export/isotopes.csv")

```